### ISSUE TITLE
[Question/Curiosity] Why some writers implement BaseRdfWriter while others IStoreWriter?

### ISSUE THREAD

**Issue by charbull** [dotnetrdf/dotnetrdf#125]
Hello,

Just out of curiosity, why some writers implement BaseRdfWriter (NTriplesWriter ) while others IStoreWriter (TriGWriter, JsonldWriter )

Thank you,
Charbel

**Comment by tpluscode** [comment]
`IRdfWriter` is an interface for writing graph formats (Turtle, n-triples, etc).
`IStoreWriter` is an interface for writing datasets (ie. multiple graphs).

And both have a twin `*Reader` interface.

**Comment by charbull** [comment]
Should any writer support both for consistency?

**Comment by tpluscode** [comment]
In theory a graph is a dataset with, well, one graph. So you potentially could have a `IStoreWriter` writer also implement `IRdfWriter` and when cast it would write to a (some?) default graph.

On the other hand some dataset serialisations are supersets of graph serialisations. Such as `n-quads > n-triples`. Ie. every n-triples document is a n-quads where all triples are in the default graph.

I wouldn't mix and match them in code though because I imagine all kinds of runtime errors and confusion and possibly inconsistency. 

Do you have some specific case in mind?

**Comment by charbull** [comment]
I have Graph object that I wanted to export in a Jsonld file to share it with an application.
So I realized, I had to pass through a Store Object and then serialize it through JsonldWriter.
So I got confused, why some writers would take an IGraph while others only IStore.

**Comment by tpluscode** [comment]
Here's a thought, we could implement a simple wrapper which would accept an `IStoreWriter` and implement `IRdfWriter` interface by writing to the store's default graph.

```c#
public class DefaultGraphWriter : IRdfWriter 
{
    public DefaultGraphWriter(IStoreWriter storeWriter)
    {
    }

    // implementation will write to storeWriter's default graph
}
```

This way you would be able write any single `IGraph` instance to a dataset serialisation format such as json-ld, n-quads, etc.

What do you think @kal, would that be useful?

**Comment by charbull** [comment]
I think it would make the writers consistent with each others :)

**Comment by kal** [comment]
I agree, it would be useful. There is an extension method for IGraph (contained in Core\Extensions.cs) that wraps a graph as a store, so the DefaultGraphWriter could use that for its implementation...so it should all be pretty straightforward...
