### ISSUE TITLE
BaseGraph#Nodes doesn't include predicate nodes

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#146]
I'm currently working on the performance of `Graph#GetUriNode` and its siblings. I notice that the [`BaseGraph#Nodes`](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Core/BaseGraph.cs#L138) method only selects subjects and objects.

Why does it not also select predicates?

**Comment by kal** [comment]
I would consider this a bug, along with the different, but related #207

**Comment by rvesse** [comment]
It's a historical artefact, I used the term Node to refer to RDF terms but in strict RDF semantics only Subjects and Objects are nodes in the graph whereas Predicates are Edges.  So its a confusion between naming and semantics...

**Comment by kal** [comment]
The problem with changing the behaviour of this propery is that it could cause some subtle and hard-to-detect issues with downstream code. I see some of this in our unit tests if you change the code there are tests that are based on the property returning only subject and predicate nodes that are then broken. 

I know that the changes we made to GetXXXNode have a similar sort of potential to break downstream code (and no-one complained about that), but I'm a bit more wary about this change.

For the 2.x API I'd propose instead to add an `AllNodes` property to the IGraph interface and document that this property returns subject, object and predicate nodes and make it clear in the documentation that `Nodes` returns only subject and object nodes.

I think when we get to a 3.0 API, that would be the point at which to break the backwards compatibility and say that IGraph.Nodes is expected to return all unique INodes in the graph, rather than those that are used as (mathematical) graph nodes.

@tpluscode , @rvesse hope this makes sense!
