### ISSUE TITLE
NON-English string not supported

### ISSUE THREAD

**Issue by shahbazwasti** [dotnetrdf/dotnetrdf#177]
Hi, 
I am facing an issue regarding languages other than English while extracting Subject and Object data from Graph to a text file. I have downloaded dbpedia dump in turtle format for Wikipedia pages . When I extract information about "Subject" and "Object" all the strings containing non-English characters are converted to symbols. For example URI "http://dbpedia.org/resource/Kansas-Nebraska_football_rivalry" if processed as simple string using Encoding.Unicode gives correct output but if same string is processed by t.Subject.ToString() method if produces following output
"http://dbpedia.org/resource/Kansas**%E2%80%93**Nebraska_football_rivalry"

I hope you can guide me where I am wrong in using this library.

Regards,

**Comment by kal** [comment]
The `ToString()` method of `UriNode` returns the `AbsoluteUri` property of the underlying C# `Uri` instance. This value is an encoded URI string which is why you see the escaped output.

To get the unescaped output I would recommend using the `Uri` property of `IUriNode` instead. Note that this property is only provided on the `IUriNode` interface so you would need to check that the node whose value you are outputting is an `IUriNode` instance and then cast (or do a safe cast and check for null).

As a one liner you could do something like this, where `n` is the INode instance you are outputting:

     (n as IUriNode)?.Uri.ToString() ?? n.ToString();

Though people reading your code later would probably thank you if you did something a bit neater ;-)
