### ISSUE TITLE
Bug? No results returned when WHERE is type Thing

### ISSUE THREAD

**Issue by DarthStem** [dotnetrdf/dotnetrdf#185]
When reasoning is used, query 1 returns results, query 2 returns nothing.

Query 1
```
SELECT ?s_ ?p_ ?o_ WHERE { ?s_ ?p_ ?o_ . { { SELECT ?s_ WHERE { ?s_ <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.sample.com/Location> . FILTER ( ?s_ = <http://www.sample.com/b79edc28-878c-44ab-9bd7-3db7d0866011> ) } ORDER BY ASC ( ?s_ ) LIMIT 1 } } }
```

Query 2
```
SELECT ?s_ ?p_ ?o_ WHERE { ?s_ ?p_ ?o_ . { { SELECT ?s_ WHERE { ?s_ <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Thing> . FILTER ( ?s_ = <http://www.sample.com/b79edc28-878c-44ab-9bd7-3db7d0866011> ) } ORDER BY ASC ( ?s_ ) LIMIT 1 } } }
```

Is this a bug?

**Comment by faubulous** [comment]
@kal Thanks for the clarification. We were able to resolve the issue and I think this can be closed. I have another question for you and I don't know where to ask: When are you planning to make the next release for dotNetRDF?

**Comment by kal** [comment]
Hi @faubulous - yeah it is difficult now that we closed the mailing list! I think you can always just open an issue here and tag it with Question for that kind of stuff for now.

I was taking a look today at the bug list and what we have received as PRs over the past few weeks. I think we have enough stuff bundled up now to make a 2.1 release and then a bunch of tasks to work on async & HttpClient stuff that can go into a 2.2 release.

So all things being equal I think we can push out a 1.10 release of VDS.Common quite soon and then update DNR dependencies and make the 2.1 release. I may get some time over the weekend to work on that.

The 2.2 release I think will probably take a few weeks - there is quite a lot of code to refactor and review.

In any case the master branch is now nice and stable so any time you need to, it should be pretty easy to pull and build locally!

**Comment by faubulous** [comment]
Thanks for the quick response, Kal! I'm just asking because we are aiming
for a release of our Trininty ORM mapper for 4th of June. It would be nice
if we could build against an official dotNetRDF NuGet package which
includes the changes to SparqlQueryGenerator by then. :-)

*Semiodesk GmbH | *Werner-von-Siemens-Str. 6 Geb. 15k, 86159 Augsburg,
Germany | Phone: +49 821 8854401 | Fax: +49 821 8854410 | www.semiodesk.com


This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Semiodesk GmbH is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2018-05-09 17:51 GMT+02:00 Kal Ahmed <notifications@github.com>:
