### ISSUE TITLE
GraphVizWriter conflates literal nodes

### ISSUE THREAD

**Issue by langsamu** [dotnetrdf/dotnetrdf#195]
h/t @lcyraphael

[This writer](https://github.com/dotnetrdf/dotnetrdf/blob/350fb42236d1c048a6503712043dd76e80d7d247/Libraries/dotNetRDF/Writing/GraphVizWriter.cs) outputs the same DOT node statement for RDF literal nodes with the same value, because it creates node identifiers [from the literal node value](https://github.com/dotnetrdf/dotnetrdf/blob/350fb42236d1c048a6503712043dd76e80d7d247/Libraries/dotNetRDF/Writing/GraphVizWriter.cs#L199).

Given
```c#
var g = new Graph();
g.LoadFromString(@"
    _:s1 <urn:p> ""o"".
    _:s2 <urn:p> ""o"".
");

new GraphVizWriter().Save(g, Console.Out);
```

this is generated:
```dot
digraph G {
"o" [shape=box];
"_:s1" -> "o" [label="urn:p"];
"o" [shape=box];
"_:s2" -> "o" [label="urn:p"];
}
```

resulting in:
![current](https://user-images.githubusercontent.com/240741/40455698-0f6bd792-5ee6-11e8-8bb3-49ef3dc6c0b4.png)

I'd expect something like this to be generated:
```dot
digraph G {
"o1" [label="o", shape=box];
"_:s1" -> "o1" [label="urn:p"];
"o2" [label="o", shape=box];
"_:s2" -> "o2" [label="urn:p"];
}
```

which would render like this:
![expected](https://user-images.githubusercontent.com/240741/40455749-3b2afaca-5ee6-11e8-8aaf-4dcc640bfa3d.png)

where node identifiers are based on the triple containing the literal.

**Comment by kal** [comment]
I suspect that for some users this might be considered to be a feature rather than a bug :-)
The RDF model has it that there is one "o" literal node in your graph that is the object of two triples, and hence the first graph is I think a bit more accurate than the second.

That said, I'd be happy to accept a PR for the GraphVizWriter that made it an option to have distinct literal nodes for every triple. Your current PR makes it the only option - do you think you could add a "DistinctLiteralNodes" option (or something like that) and make the default for it to be off?

**Comment by langsamu** [comment]
Thanks for the feedback.
I see now I would've introduced a breaking change, which I hadn't considered.

This issue of literals being distinct or not comes up every time I move between RDF (statements) and non-RDF (nodes & edges) representations of graphs.

It was good to learn about writer feature interfaces and create one for this concern.
I considered introducing it throughout the pipeline (IWriterContext, BaseWriterContext, IStoreWriteContext, BaseStoreWriterContext, GraphMLWriterContext, GraphVizWriterContext), but found the current implementations to be too inconsistent, so I wasn't confident I could do it right.
