### ISSUE TITLE
Some writers encode spaces as unicode sequences

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#197]
Looks like regression following #118.

Trying this code with dotNetRDF 2+

```c#
ITripleStore s = new TripleStore();

IGraph g = new Graph();
g.Assert(
	g.CreateUriNode(new Uri("http://example.com/base/Student/ID=10;Name=Venus Williams")),
	g.CreateUriNode(new Uri("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")),
	g.CreateUriNode(new Uri("http://example.com/base/Student")));

s.Add(g);

var tw = new System.IO.StringWriter();
new NQuadsWriter().Save(s, tw);
```

Produces URIs like `/ID=10;Name=Venus\u0020Williams` insead of `/ID=10;Name=Venus%20Williams`.

I tried some writers and this does not apply to all of them. Especially interesting is the fact that one Turtle writer works fine when the other (and TriG) doesn't 😕.

Writer affected:
* NQuadsWriter
* CompressingTurtleWriter
* Notation3Writer
* NTriplesWriter

Writer not affected:
* TriXWriter
* TriGWriter
* RdfXmlWriter
* TurtleWriter

**Comment by tpluscode** [comment]
@kal, I'm confused. I see in that other PR that this is no mistake. are you sure `/u0020` is a valid representation of spaces in an IRI? I cannot find a relevant spec...

**Comment by kal** [comment]
@tpluscode - the NTriples/NQuads spec has this as part of the IRIREF production. See https://www.w3.org/TR/n-triples/#n-triples-grammar

**Comment by kal** [comment]
I was wrong in my original assertion because the RDF 1.1 Concepts document also requires that:

> An IRI (Internationalized Resource Identifier) within an RDF graph is a Unicode string [UNICODE] that conforms to the syntax defined in RFC 3987 [RFC3987].

RFC3987 does not allow spaces in an IRI string. So my reading of this (now) is that the correct behaviour is to percent-encode characters that are not allowed in an IRI *before* applying any N-Triples encoding. So your example should produce the `/ID=10;Name=Venus%20Williams` that you were expecting.

This is what happens when you split the definition of something over three separate specifications! :-)
