### ISSUE TITLE
Linked Data Fragments

### ISSUE THREAD

**Issue by PHParis** [dotnetrdf/dotnetrdf#200]
Is there any plan to had [Linked Data Fragments](http://linkeddatafragments.org/) client?

**Comment by kal** [comment]
No plans for that at present. It would be great to add support for it though. Would probably need to think a bit about the best way to implement it, but it feels like it should be possible to create it simply as an ITripleStore implementation and then maybe use the Leviathan query engine to implement SPARQL over LDF (which would be kinda awesome...if a little laggy :-) 

Would definitely be interested in hearing from anyone willing to take on the challenge!

**Comment by sanchezja** [comment]
Kal, I'd like to look into this issue with you. I'm interested in contributing.

**Comment by kal** [comment]
Thanks @sanchezja !

So, reading through the specification documents again, the definition of a Linked Data Fragments client is quite broad. In fact DNR can be considered to be a client because it is capable of issuing SPARQL queries against an endpoint and consuming the results. However, what I assume we really want to add support for here is the separate Triple Pattern Fragments specification - is that correct? That's certainly what I was thinking of in my comments above.

Essentially it looks to me like a TPF endpoint could be treated as a readonly graph. So a client API should allow the user to specify a graph to be added by specifying the TPF endpoint and then it should follow the link headers to get to the Hydra doc for the endpoint to determine the correct way to invoke the endpoint. If the client implemented the read-only bits of the basic IGraph interface that would be the starting point to then build on. I think if we had this, we should be able to use the BaseSparqlDataset class to manage a collection of these graphs as a dataset that could be queries with Leviathan.

So it looks to me like most of the heavy lifting for this task would be in that IGraph implementation. Not quite sure how that should look right now, but I would be interested to hear your thoughts.

@tpluscode , @rvesse  feel free to chip in here too! :-)

**Comment by sanchezja** [comment]
Hi @kal ,

I'm in the process of reading the spec and other available material in order to understand the problem domain better. Looks like a good problem to solve. Will try and make better headway here soon and report back on my thoughts and questions I'm sure I'll have. For now, soaking it all in and letting it settle.

**Comment by tpluscode** [comment]
The good person to consume would be @RubenVerborgh

**Comment by RubenVerborgh** [comment]
Agree with what's written above.

How does your query engine do estimates to determine an execution plan? Because I've seen engines assume that estimates take zero time to complete, whereas in the case of TPF, you need a network request. That would be the main difference.

Otherwise, obtaining triple patterns from a TPF interface just comes down to:
- parsing its hypermedia controls to create up triple pattern lookups
- parsing the triples from a page
- chaining pages together into a single stream

**Comment by langsamu** [comment]
I've implemented a [Triple Pattern Fragments client](https://github.com/langsamu/LinkedDataFragments) along @kal & @RubenVerborgh's guidelines.

#### Example
The [following code](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments.Tests/GraphTests.cs#L40-L47)
```csharp
var g = new TriplePatternFragments.Graph("https://fragments.dbpedia.org/2016-04/en");
var o = LiteralNode("1997-02-04", XmlSpecsHelper.XmlSchemaDataTypeDate);
var triples = g.GetTriplesWithObject(o);

foreach (var triple in triples)
{
    Console.WriteLine(triple);
}
```
issues four requests (one to get metadata, three to get pages)
```sh
curl -k -i "https://fragments.dbpedia.org/2016-04/en" -H "Host: fragments.dbpedia.org" -H "Accept: application/n-quads, text/x-nquads, application/n-quads, text/x-nquads, application/x-trig, application/x-trig, application/trix, application/trix, application/ld+json, application/ld+json" -H "Connection: Keep-Alive"
curl -k -i "https://fragments.dbpedia.org/2016-04/en?object=%%221997-02-04%%22%%5E%%5Ehttp%%3A%%2F%%2Fwww.w3.org%%2F2001%%2FXMLSchema%%23date" -H "Host: fragments.dbpedia.org" -H "Accept: application/n-quads, text/x-nquads, application/n-quads, text/x-nquads, application/x-trig, application/x-trig, application/trix, application/trix, application/ld+json, application/ld+json" -H "Connection: Keep-Alive"
curl -k -i "https://fragments.dbpedia.org/2016-04/en?object=%%221997-02-04%%22%%5E%%5Ehttp%%3A%%2F%%2Fwww.w3.org%%2F2001%%2FXMLSchema%%23date&page=2" -H "Host: fragments.dbpedia.org" -H "Accept: application/n-quads, text/x-nquads, application/n-quads, text/x-nquads, application/x-trig, application/x-trig, application/trix, application/trix, application/ld+json, application/ld+json" -H "Connection: Keep-Alive"
curl -k -i "https://fragments.dbpedia.org/2016-04/en?object=%%221997-02-04%%22%%5E%%5Ehttp%%3A%%2F%%2Fwww.w3.org%%2F2001%%2FXMLSchema%%23date&page=3" -H "Host: fragments.dbpedia.org" -H "Accept: application/n-quads, text/x-nquads, application/n-quads, text/x-nquads, application/x-trig, application/x-trig, application/trix, application/trix, application/ld+json, application/ld+json" -H "Connection: Keep-Alive"
```
and produces 251 triples (same as the [DBpedia LDF query page](https://fragments.dbpedia.org/2016-04/en?object=%221997-02-04%22%5E%5Ehttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23date)).

#### Architecture
- [**`Graph`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/TriplePatternFragments/Graph.cs) is the client implemented as a read-only specialisation of [dotNetRDF's in-memory graph](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Core/Graph.cs).
I've gone for this approach instead of implementing [`IGraph`](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Core/IGraph.cs) from scratch because most of the work is done by the underlying triple-collection in both cases. If I were to implement the interface, I would be replicating existing functionality.
- [**`TripleCollection`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/TriplePatternFragments/TripleCollection.cs) is a read-only implementation of [dotNetRDF's abstract triple-collection](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Core/BaseTripleCollection.cs) that translates triple pattern methods like [`WithSubjectPredicate`](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/TriplePatternFragments/TripleCollection.cs#L103-L106) into parameterised TPF queries and returns the resulting stream of triples.
- [**`Enumerator`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/TriplePatternFragments/Enumerator.cs) is a state-machine that chains TPF pages into a single stream.
- [**`Parameters`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/TriplePatternFragments/Parameters.cs) is a domain-specific [URI Template (RFC 6570)](https://tools.ietf.org/html/rfc6570) resolver.
- [**`TripleStore`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/TriplePatternFragments/TripleStore.cs) is a utility wrapper around [dotNetRDF's in-memory triplestore](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Core/TripleStore.cs) that loads a TPF query result and splits it into [data](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/#data) and [metadata](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/#metadata).
- [**`Metadata`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/TriplePatternFragments/Metadata.cs) is a utility wrapper around [dotNetRDF's in-memory graph](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Core/Graph.cs) that exposes [metadata](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/#metadata) and [hypermedia controls](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/#controls).
- [**`IriTemplate`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/Hydra/IriTemplate.cs) is a utility wrapper for a [Hydra IRI template](https://www.hydra-cg.com/spec/latest/core/#hydra%3AIriTemplate).
- [**`IriTemplateMapping`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/Hydra/IriTemplateMapping.cs) is a utility wrapper for a [Hydra IRI template mapping](https://www.hydra-cg.com/spec/latest/core/#hydra%3AIriTemplateMapping).
- [**`ExplicitRepresentationFormatter`**](https://github.com/langsamu/LinkedDataFragments/blob/master/LinkedDataFragments/Hydra/ExplicitRepresentationFormatter.cs) is a [dotNetRDF's node formatter](https://github.com/dotnetrdf/dotnetrdf/blob/master/Libraries/dotNetRDF/Writing/Formatting/INodeFormatter.cs) implementing the `hydra:ExplicitRepresentation` [algorithm](https://www.hydra-cg.com/spec/latest/core/#example-20-the-different-variable-representations).

#### Questions
Before I integrate this into dotNetRDF, I'd appreciate some feedback.

1. Is there a better way to get metadata & hypermedia controls than requesting the base URI of the server?
This is an extra request which is practically redundant, but I haven't found any other way.
Is there some kind of autodiscovery that I'd missed?
2. How should I make the graph read-only?
Currently they throw `NotSupportedException`, but they could just not do/return anything instead.
3. How should I parse/process URI templates?
There's a [`System.UriTemplate`](https://docs.microsoft.com/en-us/dotnet/api/system.uritemplate) but only in .NET Framework, and `System.ServiceModel` is not currently a dependency of dotNetRDF.
I've used [Resta.UriTemplate](https://github.com/a7b0/uri-templates) which targets .NET Standard 2.0 and passes the [test suite](https://github.com/uri-templates/uritemplate-test).
4. What Hydra variable representation should I use and how should I decide?
I'm currently using explicit because it seems to be what servers support, but I'd rather have a proper way of deciding. 
5. Is there a TPF test suite or anything equivalent I could use to improve conformance?
6. How do I properly separate data from metadata?
My current implementation only works with providers that support multiple graphs, where data and metadata are in separate graphs. But the spec doesn't require servers to support this. For those that don't, is there a canonical or recommended way to identify the data triples and the metadata subgraph?

**Comment by RubenVerborgh** [comment]
> I've implemented a Triple Pattern Fragments client

Super!

> * Is there a better way to get metadata & hypermedia controls than requesting the base URI of the server?

Any fragment URL will do; there is no better way.

>   This is an extra request which is practically redundant, but I haven't found any other way.
>   Is there some kind of autodiscovery that I'd missed?

That _is_ the discovery ;-)
It's not redundant in the sense that it also tells you how many triples there are in total, assuming you are given the `?s ?p ?o` fragment.

> * What Hydra variable representation should I use and how should I decide?

Explict; need to distinguish between literals and URIs.

> * Is there a TPF test suite or anything equivalent I could use to improve conformance?

Not yet… I'd really like that.

> * How do I properly separate data from metadata?

Graphs.

>   My current implementation only works with providers that support multiple graphs, where data and metadata are in separate graphs. But the spec doesn't require servers to support this. For those that don't, is there a canonical or recommended way to identify the data triples and the metadata subgraph?

Only a heuristic: drop everything with Hydra predicates. Triple-based formats are not lossless, so you lose the distinction.

**Comment by pietercolpaert** [comment]
> Only a heuristic: drop everything with Hydra predicates. Triple-based formats are not lossless, so you lose the distinction.

Why not dropping everything that you used to understand the TPF controls? A different client may still want to use the other metadata in the result to do different hypermedia related tasks?

**Comment by kal** [comment]
@langsamu - a long time has passed since this came up, sorry about that! I'd still like to add TPF client support to dotNetRDF though. Is the code in a state where it could be converted to a PR? If not, no worries...I might use your repo as the basis for building the client support in dotNetRDF though (will be sure to credit you too!)

**Comment by langsamu** [comment]
> @langsamu - a long time has passed since this came up, sorry about that! I'd still like to add TPF client support to dotNetRDF though. Is the code in a state where it could be converted to a PR? If not, no worries...I might use your repo as the basis for building the client support in dotNetRDF though (will be sure to credit you too!)

I have to refresh on this.
Since then I'd implemented QPF elsewhere, so I might know better now.
I'll get back to you.

**Comment by langsamu** [comment]
@kal I had a look, upgraded dependencies, everything still works.

I think the solution is sound, I'd like to pick this up and convert to a PR.

**Comment by kal** [comment]
@langsamu that would be awesome, thank you!
