### ISSUE TITLE
UriLoader docs example throws RdfParseException

### ISSUE THREAD

**Issue by EvkaS** [dotnetrdf/dotnetrdf#249]
Hello,
I'm testing this example from the documentation, but it doesn't work:
```
IGraph g = new Graph();
UriLoader.Load(g, new Uri("http://dbpedia.org/resource/Barack_Obama"));
```

It throws `RdfParseException`:

> [Line 2233 Column 42 to Line 2233 Column 83] Unexpected Token 'Integer' encountered, expected a Property Value describing one of the properties of an Object Node

I've tried other URIs as well, but all seem to throw an exception. 
Is this a bug? It's hard to believe that the problem would be in DBpedia.

Thanks for help.

**Comment by langsamu** [comment]
# Explanation
The example fails because DBpedia serialises literals with datatype `xsd:integer` as JSON `number` literals, which the dotNetRDF JSON/RDF parser rejects.

The RDF/JSON note [says](https://www.w3.org/TR/rdf-json/#h2_section-serialization)
> If the object of the triple is an RDF Literal S [... a]dd a key called "value" with the value being the **lexical form** of S

The RDF Concepts recommendation [says](https://www.w3.org/TR/rdf11-concepts/#dfn-lexical-form)
> a lexical form [... is] a Unicode [UNICODE] **string**

The dotNetRDF RDF/JSON parser checks that property values are strings:
https://github.com/dotnetrdf/dotnetrdf/blob/ebc102106a42518da9a4a9619dac09db5dffdd9f/Libraries/dotNetRDF/Parsing/RDFJSONParser.cs#L339-L344

# Workaround
You can work around this by saying what format (other than the default RDF/JSON) you want DBpedia to respond, so parsing succeeds:
```cs
namespace UnitTestProject1
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using System;
    using System.IO;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using VDS.RDF;
    using VDS.RDF.Parsing;

    [TestClass]
    public class UnitTest1
    {
        private const string obama = "http://dbpedia.org/resource/Barack_Obama";

        [TestMethod]
        [ExpectedException(typeof(RdfParseException))]
        public void Example()
        {
            var g = new Graph();
            g.LoadFromUri(UriFactory.Create(obama));
        }

        [TestMethod]
        public void Workaround()
        {
            var g = Load(obama);
            Assert.IsFalse(g.IsEmpty);
        }

        private static IGraph Load(string uri)
        {
            // Use a client so we can specify Accept
            using (var client = new HttpClient())
            {
                // Accept: RDF/XML
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/rdf+xml"));

                using (var stream = client.GetStreamAsync(uri).Result)
                {
                    using (var reader = new StreamReader(stream))
                    {
                        var g = new Graph();
                        new RdfXmlParser().Load(g, reader);
                        return g;
                    }
                }
            }
        }
    }
}
```

# PS
Personlay I don't find it hard to believe that the problem is with DBpedia, but I'm not sure whether this is a bug or a feature. 

Some libraries [accept](http://www.easyrdf.org/converter?uri=http://dbpedia.org/resource/Barack_Obama&in=json) their serialisation, while others [don't](http://www.ldf.fi/service/rdf-grapher?rdf=http%3A%2F%2Fdbpedia.org%2Fresource%2FBarack_Obama&from=json&to=png).

**Comment by kal** [comment]
Thanks @langsamu for the investigation. I think that this is a case of the DBPedia endpoint not properly following the specification. Especially confusing because the property in question is meant to be a VIAF ID for Barak Obama  (https://viaf.org/viaf/52010985/).

@EvkaS - I think that the workaround @langsamu provides is the best way to go.
