### ISSUE TITLE
RdfXmlWriter produces invalid output for URIs with special characters

### ISSUE THREAD

**Issue by suoregnad** [dotnetrdf/dotnetrdf#255]
Hi,

at first, I would like to thank you for your development of this very useful library.
Now let's get to the point.

I am working with data sources, where some URIs contain special characters (diacritics). 
I am trying to load my data onto Fuseki triplestore via dotNetRDF. 
As I have found out, RDF/XML format is used for communication between Fuseki and dotNetRDF. Loading data from file into IGraph works just fine.

However serializing the IGraph into RDF/XML produces invalid output result and crashes on this exception:
"Unable to serialize this Graph since a Property has an unreducable URI - 'https://slovník.gov.cz/legislativn%C3%AD/sb%C3%ADrka/111/2009/pojem/m%C3%A1-adresu-s%C3%ADdla-org%C3%A1nu-ve%C5%99ejn%C3%A9-moci'"

The original URI string in my input file is following: "https://slovn\u00EDk.gov.cz/legislativn\u00ED/sb\u00EDrka/111/2009/pojem/m\u00E1-adresu-s\u00EDdla-org\u00E1nu-ve\u0159ejn\u00E9-moci"

Code:
`var g = new Graph();`
`g.LoadFromFile("...path...", new RdfXmlParser());`
`g.SaveToFile("...another/path...", new RdfXmlWriter());`

**Generated RdfXmlWriter's output** is available in given .txt file:
[rpp-data-transformed.txt](https://github.com/dotnetrdf/dotnetrdf/files/3342440/rpp-data-transformed.txt)

It has generated 61 namespace declarations, which seem to be the same. It has stopped by 62nd declaration.

**Source file** (.ttl provided as .txt): 
[rpp-data.txt](https://github.com/dotnetrdf/dotnetrdf/files/3342445/rpp-data.txt)

Thank you very much for your time.

**Comment by kal** [comment]
Hi @suoregnad!

Thanks for using dotNetRDF and for taking the time to submit this report!

Unfortunately the behaviour you are seeing is expected with RDF/XML. The problem is that the predicates in your RDF cannot be converted into XML QNames (e.g ns1:foo) because the last part of the IRI contains characters that are not allowed in an NCName in XML. This is just a complicated way of saying that there is no way to generate valid RDF/XML from your data. The RDF/XML spec acknowledges this - see https://www.w3.org/TR/rdf-syntax-grammar/#section-Serialising

You shouldn't need to use RDF/XML to communicate between Fuskei and dotNetRDF - either Turtle or NTriples should work just fine though, so I would recommend going with one of those and ditch the RDF/XML.

Cheers

Kal
