### ISSUE TITLE
RDF/XML serializes invalid names for blank nodes

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#262]
I just noticed that the recent builds produce invalid RDF/XML for blank node identifiers. Here's an excerpt or blank node with a single property:

```xml
  <rdf:Description rdf:nodeID="_:b16">
    <schema:name rdf:datatype="&xsd;string">Alan Millar</schema:name>
  </rdf:Description>
```

Notice the `_:b16` which contains disallowed characters `_:`.

According to [RDF/XML](https://www.w3.org/TR/rdf-syntax-grammar/#rdf-id) this should be an [NCName](https://www.w3.org/TR/REC-xml-names/#NT-NCName). Pretty much a string.

**Comment by kal** [comment]
Thanks for the report @tpluscode. It looks like the writer should be writing just the bnode ID (e.g. in your example just `b16`) without the Turtle syntax prefix. Would you agree?

**Comment by kal** [comment]
Hi @tpluscode  - do you have a repro for this. I just checked the relevant unit tests and the RDF/XML nodeId is generated correctly. I also just added a test for BNodes with a specific (rather than a generated) ID and that also works fine. I'm wondering if actually the problem is that the bnode ID is set as `_:b16` rather than just `b16` ?

**Comment by tpluscode** [comment]
Thanks for the hint. Turns out that it's actually json-ld.net.
