### ISSUE TITLE
Stardog Connector constructor/Stardog server GetStore does not validate store exists

### ISSUE THREAD

**Issue by joephayes** [dotnetrdf/dotnetrdf#278]
The StardogConnector constructor does not validate that store passed into it actually exists. So this code will not throw an error:

```
StardogConnector stardogConnector = new StardogConnector("http://localhost:5820", "i_dont_exist", "admin", "admin");
```

This code is called by the StardogServer GetStore method, so this code won't throw an error either:

``` 
StardogServer stardogServer = new StardogServer("http://localhost:5820", 
"admin", "admin");
IStorageProvider store = stardogServer.GetStore("i_dont_exist");
```

Not sure if this behavior is standardized at all but I think both cases should validate the store exists (or the `IsReady` property should at least return `FALSE`) because anything the user tries to do with the connector or store will fail.

Happy to contribute a PR...

**Comment by kal** [comment]
Thanks for the report!

That behaviour is actually consistent with the other connectors. All of the constructors are pretty light-weight and don't involve a roundtrip to the server. Whether that is a desireable behaviour or not is another question.

I think that the suggestion that `IsReady` should return `False` if a connection cannot be made to the server is a good one. How that is implemented will have to depend on the store being connected to because SPARQL Protocol provides no standard endpoint for checking the validity of an endpoint.

So I think a good PR would be one that implements some proper endpoint check when IsReady is called for the first time and then caches that value.
