### ISSUE TITLE
Leviathan processor gives different results for different Windows regional formats

### ISSUE THREAD

**Issue by uyha** [dotnetrdf/dotnetrdf#305]
```c#
const string update = @"
DELETE { ?s ?p ?o. }
INSERT { ?s ?p ?a. }
WHERE  { ?s ?p ?o. BIND(?o / 2 AS ?a) }
";
const string query = @"SELECT * WHERE { ?s ?p ?o.}";

var graph = new Graph();
graph.Assert(graph.CreateBlankNode(), graph.CreateBlankNode(), 0.5.ToLiteral(graph));

var store = new TripleStore();
store.Add(graph);

var updateProcessor = new LeviathanUpdateProcessor(store);
var updateParser = new SparqlUpdateParser();
updateParser.ParseFromString(update).Process(updateProcessor);

var queryProcessor = new LeviathanQueryProcessor(store);
var queryParser = new SparqlQueryParser();
var result = queryParser.ParseFromString(query).Process(queryProcessor) as SparqlResultSet;
var @object = result.First()["o"].AsValuedNode().AsDouble();
//@object is 25 when using German (Germany) regional format
//@object is 0.25 when using English (United Kingdom) regional format
```

**Comment by kal** [comment]
Thanks for the bug report. I've reproduced the error and it does look like it is an issue with the way that the literal node is formatted when it is inserted in the update.

The issue also partially also shows up for a simple query such as: `SELECT ?a WHERE { BIND (0.25 as ?a) }`. In this case the double value of the result is correct, but the string value is returned in the regional format (0,25) rather than as a SPARQL double literal string (0.25). My guess is that on update the regionally formatted string is inserted into the triple store using the regional format, but then when you query, that string value is converted to a double using the invariant format and so you get the value being interpreted as 25 rather than 0.25. I'll have to dig a bit to see where the regional formatting is being applied and why that is, but I can't think of a good reason for it to be behaving in the way it does.
