### ISSUE TITLE
Accessing UpdateExecutionTime of SparqlUpdateCommandSet can throw an exception

### ISSUE THREAD

**Issue by ghost** [dotnetrdf/dotnetrdf#306]
Hi, we are currently writing an REST API using ASP.NET and dotnetrdf. We implemented an input formatter that reads SPARQL update requests and emits a `SparqlUpdateCommandSet` which can then be used directly as a parameter of a controller method. Unfortunately, something in the ASP.NET framework inspects values emitted by input formatters and reads the `UpdateExecutionTime` field, which throws an exception because the command set has not been executed yet and results in `null` being passed to the controller.

As the field is already a `Nullable` field, would it not make more sense to return `null` if the command set has not been executed? Or maybe return `TimeSpan.Zero`?

We worked around this problem by manually setting `UpdateExecutionTime` to `TimeSpan.Zero` before returning the command set from the input formatter.

**Comment by kal** [comment]
I think if I were designing the SparqlUpdateCommandSet interface from scratch I would probably go with returning null and maybe adding another "HasExecuted" boolean flag to the class rather than throw an exception in the property getter. 

However, my worry with implementing this now is that it changes the behaviour of the class. It is definitely a thing to scope in to a 3.0 release, but it wouldn't be a backward compatible change that we could make in a point release. I think that if your workaround is solid enough for your purposes (and it sounds like it is) then I'd prefer to hold of on making any change in the 2.x releases and instead move this to the 3.0 release.

**Comment by mrf-ipt** [comment]
I think you accidentally referenced the wrong issue in the commit.

**Comment by kal** [comment]
Yes I did! Apologies.
