### ISSUE TITLE
Move to quad-store model?

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#327]
There is quite a lot of code on the 1.9 branch which moves dotNetRDF over to a model based on quads rather than triples. The quad model has some definite advantages in simplifying the interface. It also addresses issue #317 by allowing a graph name to be a node.

This would be a fundamental low-level API change that would basically require a refactor of almost the entire code-base. The code in the 1.9 branch has some backwards compatibility work in it so that the existing interfaces can be used with some restrictions (e.g. the `GraphUri` property on `Triple` is obsolete as it is replaced by `Quad` and throws a `NotSupportedException`)

**Comment by kal** [comment]
I'm in two minds about this. On the one hand I feel like it could be a really good thing to do to simplify the interface a bit. On the other hand this would be a major piece of work that I think a small team is going to find hard to work through quickly and the backwards compatibility issues would mean that the old interfaces hang around in the API anyway.

What do you think @tpluscode , @langsamu ?

**Comment by tpluscode** [comment]
I have been working exclusively working with RDF/JS model in the past year or two and it has a model quad model. The major difference between RDF/JS and dotNetRDF is in fact how it treats graphs. This has great importance for blank nodes.

For example take a piece of pseudo-code like

```js
import RDF from '@rdfjs/data-model'

const node = RDF.blankNode()

const quad1 = RDF.quad(
  bnode,
  RDF.namedNode(rdf.type),
  RDF.namedNode(schema.Person),
  RDF.namedNode('http://example.com/Graph1')
)

const quad2 = RDF.quad(
  bnode,
  RDF.namedNode(rdf.type),
  RDF.namedNode(schema.Organization),
  RDF.namedNode('http://example.com/Graph2')
)
```

You see two triples in two different named graphs. Thus, according to RDF model the subjects should not be equal. However, because the same `bnode` object was used you would still find that `quad1.subject.equals(quad2.subject)` equals true.

I have had discussions about this with people and while this is not going to change, I find this incorrect in principle and a major pitfall when working with RDF in JavaScript

I cannot really comment on the amount of work required to make the change possible but the above could be something to consider. What I liked about `Triple` + `GraphUri` model of DNR is that is provides a more accurate representation of the spec. I would not like to see that change.

**Comment by kal** [comment]
Thanks @tpluscode , its really helpful to hear about experiences of using the quad model, and I understand your concerns about ensuring that we remain accurate to the standard.

On the specific blank node issue I think that the RDF/JS folks may be correct as the [RDF Datasets section of the 1.1 spec](https://www.w3.org/TR/rdf11-concepts/#section-dataset) says that:

> Blank nodes can be shared between graphs in an RDF dataset.

So if the RDF/JS model is that the in-memory nodes are all part of a single RDF dataset, then the bnode really is the same bnode shared between those two graphs. 

The IQuad interface in the 1.9 branch of the code-base is actually a Triple + Graph model - it has a Triple property and although it provides Subject, Predicate and Object properties these get implemented as delegates to this.Triple.Subject etc.

**Comment by tpluscode** [comment]
Ah, interesting quote from the dataset spec.

That said, RDF/JS still has a problem because node comparison is really just string-based. Neither the containing graph nor dataset is really taken into account

**Comment by langsamu** [comment]
I have no experience using the quad model.
Working with DNR with and without triplestore integration, I never felt the need for a representation of quads.

I would prefer the core library to remain true to the spec with triples.

**Comment by kal** [comment]
Thanks both of you. I think that given your responses and the fact that we've not had anyone complain about the lack of a quad model, then we can probably pass on this change for now and keep the existing model with triples + graph.
