### ISSUE TITLE
How to inject bindings into SparqlQuery

### ISSUE THREAD

**Issue by giacomociti** [dotnetrdf/dotnetrdf#379]
I have a request similar to #377 . My aim is to inject bindings into an existing query. I see InlineDataBuilder has an AppendTo method which  looks like what I am looking for, but the class is internal. I am missing any alternative way to achieve my goal? Thanks

**Comment by giacomociti** [comment]
Just to clarify a bit, what I can do at the moment is to cheat and call the method by reflection:

```csharp   
static string InjectValuesToQuery(IReadOnlyCollection<Uri> values, string unboundQuery, string variable)
{
    var query = new SparqlQueryParser().ParseFromString(unboundQuery);
    var builder = QueryBuilder.SelectAll().InlineData(variable);
    values
        .Aggregate(builder, (b, v) => b.Values(v))
        .GetType()
        .GetMethod("AppendTo", new[] { typeof(GraphPattern) })
        .Invoke(builder, new[] { query.RootGraphPattern });
    return query.ToString();
}
```

**Comment by kal** [comment]
Hi Giacomo,

The problem with adding the AppendTo method to the public IInlineDataBuilder interface is that it would pollute the builder API with concerns that are to do with modifying a query rather than building a query from scratch.

I think in your case it might be easier to work directly with the parsed SparqlQuery rather than go through the QueryBuilder. 
It still needs a few changes to the API, but if the methods were public you could directly call GraphPattern.AddInlineData(BindingsPattern) to insert a VALUES binding (the AddBindingTuple method on BindingsPattern would also have to be made public rather than internal to support this).  This feels like a better match to what you are trying todo (i.e. to modify a parsed query as opposed to build a new query).

**Comment by giacomociti** [comment]
Hi @kal , thanks for your response.

My use case is definitely not related to query creation, so I agree to not pollute the builder interfaces and focus instead on SparqlQuery. I would also consider SparqlParametrizedQuery since injecting values is akin to passing array parameters, but I guess this is more complex than token replacement and relying on a properly parsed query is much easier and safer.
