### ISSUE TITLE
TriG parser doesn't support dot in URI

### ISSUE THREAD

**Issue by PravinPrameKumar** [dotnetrdf/dotnetrdf#439]
code (tried all three TriGSyntax):
```
TriGParser parser = new TriGParser();
TripleStore store = new TripleStore();
parser.Load(store, filePath);
```

data:
```
@prefix test: <http://www.test.com/test/1.0#> .
{
test:apple a test:Fruit .
test:cool.orange a test:CoolFruit .
}
```

exception thrown:
```
{"[Line 5 Column 17] Unexpected input 'orange', expected a QName, the 'a' Keyword or a Plain Literal"}
   at VDS.RDF.Parsing.Tokens.TriGTokeniser.TryGetPlainLiteralOrQName()
   at VDS.RDF.Parsing.Tokens.TriGTokeniser.GetNextToken()
   at VDS.RDF.Parsing.Tokens.BufferedTokenQueue.BufferInternal()
   at VDS.RDF.Parsing.Tokens.BufferedTokenQueue.Peek()
   at VDS.RDF.Parsing.TriGParser.TryParseTriples(TriGParserContext context, Uri graphUri)
   at VDS.RDF.Parsing.TriGParser.TryParseGraph(TriGParserContext context)
   at VDS.RDF.Parsing.TriGParser.Parse(TriGParserContext context)
   at VDS.RDF.Parsing.TriGParser.Load(IRdfHandler handler, TextReader input)
   at VDS.RDF.Parsing.TriGParser.Load(ITripleStore store, TextReader input)
   at VDS.RDF.Parsing.TriGParser.Load(ITripleStore store, String filename)
```

Whereas this works with the Turtle parser:
code:
```
Graph g = new Graph();
TurtleParser tparser = new TurtleParser();
tparser.Load(g, filePath);
```

data:
```
@prefix test: <http://www.test.com/test/1.0#> .
test:apple a test:Fruit .
test:cool.orange a test:CoolFruit .
```

Would appreciate advice on how to get around this issue. Thanks.

**Comment by kal** [comment]
Hi Pravin,

Unfortunately there isn't an easy workaround for this issue. I have been working on the TriG parser recently as part of the work on version 3.0 and quite a lot of that work has been in improving the parser's conformance with the TriG 1.1 specification.  

How urgent is this issue for you? Are you able to work around this issue by switching syntaxes to NQuads instead of TriG? I'm just wondering if I should try to backport the changes to the 2.x release or if you are able to get by for now and wait for the 3.0 release.

**Comment by PravinPrameKumar** [comment]
Hi Kal, thanks for your reply and suggestion. This is not urgent for me and I was able to work around this successfully by using NQuads. Thanks

**Comment by PravinPrameKumar** [comment]
Hi Kal, this has come up again, and I'm wondering if there's an ETA on a version 3 with a fix for this issue?
Thanks

**Comment by kal** [comment]
This is fixed in the current pre-release version of dotNetRDF 3.0. A final release isn't too far away now but will depend on how much free time I get in the coming weeks

**Comment by PravinPrameKumar** [comment]
Ok, no worries. I did try a 3.X version at the time of my comment and got the same problem, but you must have made some changes since then. Should I raise another issue for the lack of encoded character handling in URIs, or are you already across that?

**Comment by kal** [comment]
Hi @PravinPrameKumar - I did do some updates to the TriG parser since then to get it to pass the RDF 1.1 test suite and to update it in line with other changes in the library. There was another report of this issue on #542 which I actually added an explicit test for, so that should be fixed.

Handling of encoded characters should also be improved now, but please do open another issue if you find it is still a problem with the latest 3.0 release candidate (its RC0006 in NuGet now).
