### ISSUE TITLE
Query against an UnionGraph is taking too much time or doesn't yield

### ISSUE THREAD

**Issue by rubesh-panda** [dotnetrdf/dotnetrdf#455]
Created an `UnionGraph` where the default graph is loaded from a .ttl file and the other graph is just the inferred result of the default graph. The reason behind using a UnionGraph is that to query against the inferred graph and add triples back to the original graph, so I want to keep the two distinct.

```
var originalGraph = new Graph();
var ttlParser = new TurtleParser();
ttlParser.Load(originalGraph, new StringReader(turtleText)) //turtleText is the RDF content from a file

var inferredGraph = new Graph();
var rdfsReasoner = new StaticRdfsReasoner();
rdfsReasoner.Initialise(originalGraph); //the original Graph have the ontology definitions
rdfsReasoner.Apply(originalGraph, inferredGraph); 

//Merge original triples with inferred triples onto a new graph which will be used for querying
var inferredGraphWithOriginalContent = new UnionGraph(originalGraph, new[] { inferredGraph });
```

For a smaller dataset, query against the `UnionGraph (inferredGraphWithOriginalContent)` takes some time. However for a larger dataset query against the `UnionGraph` never yields.

To get around this issue, I came up with following
```
//Loop through the triples and copy to new graph
var inferredGraph = new Graph();
foreach (var triple in originalGraph.Triples)
{
    inferredGraph.Assert(triple.CopyTriple(inferredGraph));
}

var rdfsReasoner = new StaticRdfsReasoner();
rdfsReasoner.Initialise(inferredGraph);
rdfsReasoner.Apply(inferredGraph);
```
Query against the above inferred graph executes quickly.

**Comment by kal** [comment]
I think that the behaviour you are seeing is because the `UnionGraph` is not an indexed graph and even if the graphs it is providing the union over are all indexed the lookups are not using those indexes.

Fortunately there is an alternative approach which will preserve the separation of graphs and give you the indexed speed. Create an `InMemoryDataset` instance using the overload that accepts a boolean `unionDefaultGraph` parameter (set to `true`) and add your graphs (original and inferred) to that. You will need to ensure that at least one of those two graphs has a name assigned to it. Then use that as the input dataset for the query engine. The code will look something like this (skipping graph and SPARQL query creation):

```c#
var dataset = new InMemoryDataset(true);
dataset.AddGraph(g);
dataset.AddGraph(inferred);
var queryEngine = new LeviathanQueryProcessor(dataset);
var result = queryEngine.ProcessQuery(query);
```

In my local testing this approach is much faster than then `UnionGraph` approach and just a little bit slower than the single graph approach as the graph indexes are being used and so there is just the overhead of additional index lookups rather than full triple scans.

**Comment by rubesh-panda** [comment]
Thanks @kal the provided alternative approach worked.
