### ISSUE TITLE
FileVersion in dotNetRDF.dll

### ISSUE THREAD

**Issue by giacomociti** [dotnetrdf/dotnetrdf#474]
The FileVersion attribute of dotNetRDF.dll is 0.0.0.0 in dotnetrdf.2.7.3.nupkg.
It was 2.7.2.0 in dotnetrdf.2.7.2.nupkg

**Comment by kal** [comment]
Thanks @giacomociti ! It was an unfortunate side-effect of trying to do the NuGet release manually for this build. I've updated the GitHub workflow on the 2.x branch so that the AssemblyInfo files are updated by GitVersion as well as sorting out the API key for automatically pushing the packages to nuget.org, so hopefully this shouldn't happen again 🤞 !

This will result in a 2.7.4 release on NuGet because they don't allow patch versions AFAIK.
