### ISSUE TITLE
Missing GraphEventHandler for change, merged and cleared graphs actions in BaseGraphCollection

### ISSUE THREAD

**Issue by amanullahusmani** [dotnetrdf/dotnetrdf#515]
In contrast to `BaseTripleStore` implementation, `BaseGraphCollection` is missing implementation of `GraphEventHandler` for graph changed, merged or cleared.

The change request impacts `BaseGraphCollection`, `GraphCollection` and `PersistentGraphCollection`. 

When a graph is added that already exists in `GraphCollection`, `Add(IGraph g, bool mergeIfExists)` should raise something like `this.RaiseGraphMerged(g)` [here](https://github.com/dotnetrdf/dotnetrdf/blob/ebba0448930fcdce4d507e69bacc0cfb9e6ac80b/Libraries/dotNetRdf.Core/Core/GraphCollection.cs#L96). Currently if a graph with `IRefNode` already exists in `_graphs` collection, merging/updating/clearing graph won't add any pending `_actions` to that list (i.e. example of [RaiseGraphAdded](https://github.com/dotnetrdf/dotnetrdf/blob/ebba0448930fcdce4d507e69bacc0cfb9e6ac80b/Libraries/dotNetRdf.Core/Core/PersistentGraphCollection.cs#L66)) that should be used flushed to the database [here](https://github.com/dotnetrdf/dotnetrdf/blob/ebba0448930fcdce4d507e69bacc0cfb9e6ac80b/Libraries/dotNetRdf.Core/Core/PersistentGraphCollection.cs#L324).

**Comment by kal** [comment]
I think that this makes sense. I will need to check through the GraphCollection semantics to ensure that raising these events won't break anything but at first glance I think we should add this to 3.0

**Comment by kal** [comment]
Going through the implementation, I'm not quite sure if there is a real problem here. A graph merge, graph clear and graph change are all handled by PersistentGraphCollection as triple-level events. As long as your underlying store supports Update, these operations result in TripleStorePersistenceAction instances getting added to _actions. If your underlying store doesn't support Update then this doesn't happen as there isn't a way to persist the changes through to the store.

Can you elaborate some more on what you are trying to do and where the problem arises - perhaps I have missed something.

**Comment by kal** [comment]
Closing due to lack of further information.
