### ISSUE TITLE
Issues with ValidateLanguageSpecifiers

### ISSUE THREAD

**Issue by IS4Code** [dotnetrdf/dotnetrdf#565]
After updating to 3.0, I found a couple of situations where the application crashed as a result of an invalid BCP 47 tag encountered, specifically one such case was `"x-default"` and the other was `""` (empty string). These tags are extracted from other sources (such as HTML documents) and may therefore contain arbitrary values; I would much rather validate such values myself than to have the application crash from a handler somewhere deep inside. Moreover, some handlers don't appear to expose any way to control it, for example `WriteThroughHandler` which does not appear to offer such option, since there is no way to provide the factory through its constructor (I would have to derive from it and access the protected member).

Here are my opinions on the matter:

* `"x-default"` and `""` should not be rejected as input. RDF mandates the tags must be [well-formed](https://www.rfc-editor.org/rfc/rfc5646.html#section-2.1), and `"x-default"` conforms to `privateuse` and is therefore well-formed. As for the empty string, I think it is reasonable to treat it simply as an untagged plain string literal, as is done in many other places.
* `ValidateLanguageSpecifiers` should be `false` by default, or its addition should be mentioned in the [3.0 Change Notes](https://dotnetrdf.org/docs/3.0.x/user_guide/3_0_changelog.html) and there should be a global configuration option to disable it.
* `WriteThroughHandler` should have an `INodeFactory`-accepting constructor (and potentially other services like `IUriFactory).
* Either `BaseRdfHandler` or `BaseHandler` could have a `ValidateLanguageSpecifiers` property that accesses the inner node factory, like with `NormalizeLiteralValues` and `BaseUri`. This will probably only work when the node factory is `NodeFactory` specifically, and could throw an exception otherwise.

**Comment by kal** [comment]
With regards to the validation. I agree that privateuse should be validated and that's a bug. I disagree with validating the empty string as I don't think the empty string should necessarily be treated the same as null. When you say that is the case in other places, do you mean in the dotNetRDF code-base?

I think validation should be on by default because it is part of the RDF 1.1 specification that language tags should be well formed, but it should be possible to disable that validation if you know what you are doing. You are correct that it should be documented though.
 
I want to avoid reintroducing global configuration values so would prefer to go down a route that uses either properties or constructor injection. I really should have updated all of the classes that derive from `BaseRdfHandler` to provide a way to inject the `INodeFactory` instance to be used in the 3.0 release, so that is definitely an oversight that needs to be fixed for `WriteThroughHandler` and possibly some other classes too.

The validation of language specifiers is currently part of the NodeFactory responsibility (in the long term I think separating validation from node construction would be a good idea, but that's something to consider for a 4.0 release), so I think it makes most sense to keep that as the way to control whether the validation happens or not. We could extend the `INodeFactory` interface to require it to expose a `ValidateLanguageSpecifiers` flag, but again that would be a breaking API change which I wouldn't want to introduce in a bug fix release, so I think adding constructor parameters where they are missing is the best way to address this issue in the 3.x release.

**Comment by kal** [comment]
Hi,

Firstly you definitely don't appear nagging. Its really great to have engaged users who raise issues and provide fixes and suggestions! So please keep it up! :)

Re empty string, I went and had a dig into the source code to see what we do when an empty string is passed as the language specifier and the implementation in `BaseLiteralNode` does treat a literal with an empty language specifier as being a simple string literal. So in that case I agree with you that it makes sense that the validation should allow an empty string literal, but then on the other hand the Turtle syntax requires a minimum of a single character! :exploding_head: 

I think overall my thought would be that the validation should treat an empty string as a valid "not present" language tag and only apply the validation rules to a non-empty string.

However I do think that it makes sense to try to validate to the ABNF in BCP47 even though that is more complex than the simple Turtle validation. My reason for that is that the RDF 1.1 specification does make this a requirement (see the section [Literals](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal)). However, supporting a more lax validation also makes sense and having it as an optional form of validation that library users can enable if they know what they are doing is something that makes sense to me.

I'm not sure if with the `Bcp47Strict` option you are thinking of a validation that ensures that the language tag is `valid` (as opposed to the more lax `well-formed`) as defined in BCP47? While that would be a nice to have, I think that just `None`, `Turtle` and `WellFormed` would be enough options for validation at this stage.

**Comment by IS4Code** [comment]
Yes, treating empty string as "not present" is what I had in mind. As for `Bcp47Strict`, this is pretty much `WellFormed`, but for `Bcp47Loose` I meant something without maximum length checks. I.e. `x-aaaaaaaa` is well-formed, but `x-aaaaaaaaa` is not, so my idea was to basically use the same regex but without those checks. It might not be needed though, since `Turtle` (or a more descriptive name) might be pretty much equivalent with the effect.
