### ISSUE TITLE
variable name affects query result

### ISSUE THREAD

**Issue by giacomociti** [dotnetrdf/dotnetrdf#571]
I'm facing something strange: renaming variable `?sub` to `?c`, the following query fails to return the solution:

```fsharp
#r "nuget: dotNetRdf.Core"

open VDS.RDF
open VDS.RDF.Parsing

let graph = new Graph()

StringParser.Parse(graph, "
@prefix : <http://example.org/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

:age rdfs:domain :Person .
")

// correctly find the solution
graph.ExecuteQuery("
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT *
WHERE {
    ?property rdfs:domain ?class .
    ?sub rdfs:subClassOf* ?class .
}")

// renaming variable ?sub to ?c the solution is not returned anymore
graph.ExecuteQuery("
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT *
WHERE {
    ?property rdfs:domain ?class .
    ?c rdfs:subClassOf* ?class .
}")
```

after some [experiments](https://gist.github.com/giacomociti/8d11c0d8ad8917474d2858fcafd80d9c) (sorry, the gist is F# because it was easier for me to experiment interactively) I think I found that the issue is present with the variable name 'less than' "property".

So, more generally, the name of the variable in subject position in the first pattern (`?property` in the examples) should lexicographically precede the variable in subject position of the second pattern (`?sub` and `?c` in the examples)

**Comment by kal** [comment]
My best guess is that the optimiser is ordering the patterns differently when you have different variable names and when you order it so that the property path is evaluated first, the property path evaluation is incorrectly binding 0 results (whereas it should be binding all subject nodes to themselves). I'll need to check on this in the debugger, but if my guess is correct I suspect that disabling the optimiser would be a simple workaround for now.
