### ISSUE TITLE
Writing with GraphViz output writer fails on simple example

### ISSUE THREAD

**Issue by FelixReuthlinger** [dotnetrdf/dotnetrdf#583]
I just tried to use the GraphVizWriter (using dotNetRdf v 3.0.1), but it even fails on a very simple example:

```
IGraph graph = new Graph();

ILiteralNode requiredFor = new LiteralNode("required for");
ILiteralNode crafts = new LiteralNode("crafts");

ILiteralNode wood = new LiteralNode("wood");
ILiteralNode stone = new LiteralNode("stone");
ILiteralNode hammer_recipe = new LiteralNode("recipe for a hammer");
ILiteralNode hammer = new LiteralNode("hammer");

graph.Assert(new Triple(wood, requiredFor, hammer_recipe));
graph.Assert(new Triple(stone, requiredFor, hammer_recipe));
graph.Assert(new Triple(hammer_recipe, crafts, hammer));

GraphVizWriter dotWriter = new GraphVizWriter();
dotWriter.Save(graph, Path.Combine(Paths.ConfigPath, "file.dot"));
```

raises this exception:
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
VDS.RDF.Writing.GraphVizWriter.WriteTriple (VDS.RDF.Triple triple, VDS.RDF.Writing.Contexts.BaseWriterContext context, System.Boolean collapseLiterals) (at <d7c34e9719bc4903ae0f8cbb8cc1093e>:0)
VDS.RDF.Writing.GraphVizWriter.WriteGraph (VDS.RDF.Writing.Contexts.BaseWriterContext context, System.Boolean collapseLiterals) (at <d7c34e9719bc4903ae0f8cbb8cc1093e>:0)
VDS.RDF.Writing.GraphVizWriter.SaveInternal (VDS.RDF.IGraph g, System.IO.TextWriter output) (at <d7c34e9719bc4903ae0f8cbb8cc1093e>:0)
VDS.RDF.Writing.BaseRdfWriter.Save (VDS.RDF.IGraph g, System.IO.TextWriter output, System.Boolean leaveOpen) (at <d7c34e9719bc4903ae0f8cbb8cc1093e>:0)
VDS.RDF.Writing.BaseRdfWriter.Save (VDS.RDF.IGraph g, System.IO.TextWriter output) (at <d7c34e9719bc4903ae0f8cbb8cc1093e>:0)
VDS.RDF.Writing.GraphVizWriter.Save (VDS.RDF.IGraph g, System.String filename) (at <d7c34e9719bc4903ae0f8cbb8cc1093e>:0)
...
```

Any clue what I might be missing? the NRE does not help in such case ;)

**Comment by kal** [comment]
Hi Felix

The issue is that you are using literal nodes for subject and objects of triples. In standard RDF the subject of a triple must be either a URI node or a blank node and the predicate must be a URI node. Literals can only appear in the object position.

In your case I would use URI nodes for pretty much everything because you are going to want one unique URI identifier for each material and each product. Here's a really simple rewrite of your code that uses a single flat URI namespace ("http://example.org/") for all the identifiers - in reality you might want to separate out raw materials and constructed materials and you might also want to add some more triples that give labels to the resources (these would be literal nodes).

```
IGraph graph = new Graph();
graph.NamespaceMap.AddNamespace("ex", UriFactory.Create("http://example.org/"));

IUriNode requiredFor = graph.CreateUriNode("ex:requiredFor");
IUriNode crafts = graph.CreateUriNode("ex:crafts");

IUriNode wood = graph.CreateUriNode("ex:wood");
IUriNode stone = graph.CreateUriNode("ex:stone");
IUriNode hammer_recipe = graph.CreateUriNode("ex:recipeForAHammer");
IUriNode hammer = graph.CreateUriNode("ex:hammer");

graph.Assert(new Triple(wood, requiredFor, hammer_recipe));
graph.Assert(new Triple(stone, requiredFor, hammer_recipe));
graph.Assert(new Triple(hammer_recipe, crafts, hammer));

GraphVizWriter dotWriter = new GraphVizWriter();
dotWriter.Save(graph,"file.dot");
```

BTW - we probably should validate that the expected types of nodes are passed into the Triple constructor so as to at least provide you with a meaningful error message, or better still change the signature of the constructor to be much more typesafe so that you get a compile time error. I'm going to create a ticket for that.

**Comment by kal** [comment]
Hi Felix,

You can look at URI nodes in one of two ways:

1. You can take the linked data perspective that this is a great way to publish your data on the web using stable globally unique identifiers. There's a short series of articles on [LinkedDataTools.com](https://www.linkeddatatools.com/semantic-web-basics/) that take this perspective. If you go down this route it is also worth considering if there are existing vocabularies you can use rather than inventing your own identifiers for types and properties.

2. Alternatively you can take the more "internal" perspecitve that a URI is just an identifier, which you are in effect creating anyway by naming a node `hammer_recipe`. Indeed you can use URN notation for your URI nodes - you aren't restricted to using HTTP/S URIs by any means. URNs can use a "private" schema so you could use a URN like `urn:x-recipe-manager:hammer_recipe`. While writing this I also came across [this SO answer](https://stackoverflow.com/questions/13904733/look-for-unique-id-pattern-which-easy-indexed-by-search-engines/13948816#13948816) that talks about Tag URIs which might also work for you? In any case I wouldn't let the need to use URIs necessarily put you off using RDF.

Blank Nodes are a bit of a special case. Generally you use them when you want to have a thing with some properties but you don't want to coin an identifier for it. The downside of blank nodes is that they have no stable identifier so are hard to manipulate and to update. They are useful if you have structured values that you are always going to update by doing a full replacement, but generally I'd avoid them unless you know that you can get away with using them.
