### ISSUE TITLE
CompressingTurtleWriter only replaces some URIs

### ISSUE THREAD

**Issue by fschumac** [dotnetrdf/dotnetrdf#61]
I export a simple Graph with CompressingTurtleWriter and setting the used namespace. Although the output turtle uses the namespace for some of the Uris, it doesn't use it for all the Uris. Am I missing something? I don't see a logic behind this behavior. Here is the output file: 

res: http://creativeartefact.org/musicdataextractor/ is only replaced on some Uris

> @base http://creativeartefact.org/.
> 
> @prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#.
> @prefix rdfs: http://www.w3.org/2000/01/rdf-schema#.
> @prefix xsd: http://www.w3.org/2001/XMLSchema#.
> @prefix mbo: http://creativeartefact.org/ontology/.
> @prefix res: http://creativeartefact.org/musicdataextractor/.
> 
> http://creativeartefact.org/musicdataextractor/02d20c87-58c9-41c4-b2a2-17d69b3b12b4 mbo:hasReleaseGroup http://creativeartefact.org/musicdataextractor/2b20e5f0-d381-455d-801e-dd74f48306ba,
>                                                                                                           http://creativeartefact.org/musicdataextractor/35b728ff-e1d6-413a-a410-faee298777f1,
>                                                                                                           res:faa4f1a6-7798-440f-9e7b-b0426d6f0162;
>                                                                                       a mbo:Artist;
>                                                                                       rdfs:comment "Symphonic Opera Metal from Leipzig";
>                                                                                       rdfs:label "molllust".
> http://creativeartefact.org/musicdataextractor/2b20e5f0-d381-455d-801e-dd74f48306ba a mbo:ReleaseGroup;
>                                                                                       rdfs:label "Bach con fuoco".
> http://creativeartefact.org/musicdataextractor/35b728ff-e1d6-413a-a410-faee298777f1 a mbo:ReleaseGroup;
>                                                                                       rdfs:label "In Deep Waters".
> res:faa4f1a6-7798-440f-9e7b-b0426d6f0162 a mbo:ReleaseGroup;
>                                          rdfs:label "Schuld".

**Comment by rvesse** [comment]
Not all URIs can be compacted into prefixed name form because of restrictions in the Turtle grammar as to what characters may appear in the local name portion. More specifically the original version of turtle specify the grammar for compatibility with RDF/XML. In XML local names cannot begin with a numeric character so turtle also has this restriction.

The new version of the turtle specification does permit a wider range of characters including starting with a numeric character. However the library defaults to outputting data using the older specification to maximise portability of data. If you have an instance of a Turtle writer you can set the syntax to use the newer version which should compact all URIs in your example data.

    IRdfWriter writer = new CompressingTurtleWriter(TurtleSyntax.W3C);

**Comment by kal** [comment]
Question answered.
