### ISSUE TITLE
XML version error when trying simple AllegroGraphConnector query.

### ISSUE THREAD

**Issue by mayfairstrange** [dotnetrdf/dotnetrdf#668]
When doing a simple query to my AllegroGraph store using `AllegroGraphConnector `I get the following error:

`Version number '1.1' is invalid. Line 1, position 16.`

Please see my SO question: [stackoverflow]( https://stackoverflow.com/questions/79152172/dotnetrdf-allegrographconnector-xml-error-when-querying)

`AllegroGraphConnector` seems to not support XML 1.1?

Thank you in advance for any replies.

**Comment by kal** [comment]
Sorry for the delay in responding to this. I've posted a comment on your SO question, but I'm afraid I don't really have a good answer to the problem. The issue is that Allegrograph is now returning XML results with an XML 1.1 version declaration at the top. .NET's XML parser does not handles XML 1.1 and throws an exception when it sees that header and there does not seem to be anyway to disable that behaviour (see https://stackoverflow.com/questions/17231675/does-net-4-5-support-xml-1-1-yet-for-characters-invalid-in-xml-1-0).

I don't know enough about Allegrograph, but I wonder if it might be possible to configure the server to return XML using XML 1.0 for compatibility purposes. 

Another possibility would be to ask for results in a non-XML format (e.g.  JSON instead of XML for SPARQL and Turtle instead of RDF/XML for RDF), but there is not currently an easy way to configure the Accept headers that go out on a request from the Allegrograph connector. That is maybe a new feature we could add, or perhaps just set up the Allegrograph connector with a connector-specific accept header for requests.

**Comment by kal** [comment]
I've implemented a "fix" (actually more of a work-around) for this issue. The AllegroGraph connector now asks for JSON format SPARQL results only and so does not receive the un-parseable XML.
