### ISSUE TITLE
Bring back CI

### ISSUE THREAD

**Issue by tpluscode** [dotnetrdf/dotnetrdf#75]
Back in the day we used my TeamCity too build dnr and run tests. @kal, are you now only running that stuff locally?

I think we should move forward and set up Appveyor. I remember that some tests would fail intermittently (such that relied on dbpedia, etc). Some of them also took quite long. We'll have ignore those tests from running on CI because Appveyor has a limit of 30 minutes for build

**Comment by kal** [comment]
Yep, currently I just run the tests locally. 

A little while ago I got the BrightstarDB build running on AppVeyor, but it is currently broken again because they made some changes to their Xamarin support :-(. However, I like the system and its integration into GitHub and I think it makes sense to do the work necessary to get a build working. I'd be up for doing this, perhaps once we have completed work on #76

**Comment by tpluscode** [comment]
I guess that we could start experimenting on that as soon as I push a half-done branch for #76. Should be later this week.

**Comment by kal** [comment]
Yes definitely!
