### ISSUE TITLE
StardogConnector enhancement

### ISSUE THREAD

**Issue by charbull** [dotnetrdf/dotnetrdf#96]
Hi,

StardogConnector can only connect for now to an existing KB (database). 
A good enhancement would be to allow the creation of a new KB (database) through dotNetRDF.

Thank you,

**Comment by kal** [comment]
Will have to look at this in a bit more detail. I know that there are quite a few options available when setting up a new Stardog KB - my guess is that this is one reason why the create option is not currently implemented because it would mean implementing quite a lot of configuration API.

Happy to accept PRs on this though ;-)

**Comment by charbull** [comment]
If you have any pointers on how I can get started, it would be cool :)

**Comment by kal** [comment]
I had a dig in the code and found VDS.RDF.Storage.Management.BaseStardogServer which has methods for managing KBs. The code is in the file Libraries\dotNetRDF\Storage\Management\StardogServer.cs

So start there and see if that actually has the functionality you need.

**Comment by charbull** [comment]
It seems this is already supported through the StardogServer API
```C#
            StardogServer stardogServer = new StardogServer("http://localhost:5820", "admin", "admin");
            IStoreTemplate iStoreTemplate = new StardogDiskTemplate(storeId);
            stardogServer.CreateStore(iStoreTemplate);
```
It is enough for now, will close it
